### ISSUE TITLE
First start did fail

### ISSUE THREAD

**Issue by vkuehn** [FedericoCeratto/shoebill#5]
Simply did the following stepps

pelican-quickstart
git init .
git commit -am "first"
shoebill ./

ended in that error
Starting Shoebill...
Traceback (most recent call last):
  File "/home/linuxuser/venv/shoebill/bin/shoebill", line 11, in <module>
    load_entry_point('shoebill==1.0.1', 'console_scripts', 'shoebill')()
  File "/home/linuxuser/venv/shoebill/lib/python3.8/site-packages/shoebill/__init__.py", line 545, in main
    aaa = Cork(auth_dir, preferred_hashing_algorithm="scrypt")
TypeError: __init__() got an unexpected keyword argument 'preferred_hashing_algorithm

**Comment by vkuehn** [comment]
dead project
